### ISSUE TITLE
得到新6星角色資料

### ISSUE THREAD

**Issue by Danny05170** [acygen/PCRDMMMOD#1]
大佬你好 請問如果我想得到新的6星角色 例如6星毛二力 我可以怎做？ 因為現時版本如果我把毛二力調6星 會不可以進入會戰畫面

感謝解答！！

**Comment by acygen** [comment]
毛二力六星的话首先manifest的资源文件版本得是有毛二力6星的版本，数据库版本也必须是出了6星后的版本。之前版本的数据库没有六星的数据所以会卡死。

**Comment by Danny05170** [comment]
大佬具體怎樣更新manifest?  

https://www.acygenbot.xyz/2022/03/01/%E5%85%AC%E4%B8%BB%E8%BF%9E%E7%BB%93dmm%E7%AB%AF%E7%9A%84mod%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B%EF%BC%88%E4%B8%89%EF%BC%89/

在這網中 "所以想要变更版本，只需要修改代码" , 具體是修改哪裡的? 謝謝

**Comment by acygen** [comment]
manifest是在本地streamingAssest/manifest文件夹里，你只要从日服官网上下载新的替换本地的即可

**Comment by Danny05170** [comment]
大佬所指的日服官网是哪個@@?

**Comment by limgw97** [comment]
How can I get the exe file of this? lol the website is already dead
