### ISSUE TITLE
Hello I want to get this program.

### ISSUE THREAD

**Issue by limgw97** [acygen/PCRDMMMOD#5]
Hello, I'm a player who plays in Korean server. long ago, I got this program's old version from somewhere. It was very useful. so I want to get this program's most recent version. Because your private page was crashed, I can't contact you lol my wechat ID is wxid_wtmfgtgnkvt322. I can't make qq ID because I'm a foreigner. I'm looking forward your contact. please help me

**Comment by acygen** [comment]
You can try another tool to calculate clan battle.(PCRCalculator)
[download.txt](https://github.com/acygen/PCRDMMMOD/files/9791064/download.txt)

**Comment by limgw97** [comment]
Ah okay thank you for replying lol

**Comment by limgw97** [comment]
May I ask you what the password is?

**Comment by acygen** [comment]
223333

limgw97 ***@***.***> 于2022年10月15日周六 12:05写道：
